/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client.views;

import javax.swing.JOptionPane;

/**
 *
 * @author Mariele
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistros = new javax.swing.JMenu();
        registroPetItem = new javax.swing.JMenuItem();
        registroTutorItem = new javax.swing.JMenuItem();
        registroAdocaoItem = new javax.swing.JMenuItem();
        CadUsuario = new javax.swing.JMenuItem();
        menuListagens = new javax.swing.JMenu();
        listagemPetItem = new javax.swing.JMenuItem();
        listagemTutorItem = new javax.swing.JMenuItem();
        listagemAdocaoItem = new javax.swing.JMenuItem();
        ListarUsuarios = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        relatorioPetItem = new javax.swing.JMenuItem();
        relatorioTutorItem = new javax.swing.JMenuItem();
        relatorioAdocaoItem = new javax.swing.JMenuItem();
        menuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 102, 255));
        setMinimumSize(new java.awt.Dimension(451, 503));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/src/assets/logotipoAdotePet.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        menuRegistros.setText("Registros");

        registroPetItem.setText("Novo pet");
        registroPetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroPetItemActionPerformed(evt);
            }
        });
        menuRegistros.add(registroPetItem);

        registroTutorItem.setText("Novo tutor");
        registroTutorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroTutorItemActionPerformed(evt);
            }
        });
        menuRegistros.add(registroTutorItem);

        registroAdocaoItem.setText("Nova adoção");
        registroAdocaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroAdocaoItemActionPerformed(evt);
            }
        });
        menuRegistros.add(registroAdocaoItem);

        CadUsuario.setText("Novo usuário");
        CadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadUsuarioActionPerformed(evt);
            }
        });
        menuRegistros.add(CadUsuario);

        jMenuBar1.add(menuRegistros);

        menuListagens.setText("Listagens");

        listagemPetItem.setText("Listar pets");
        listagemPetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemPetItemActionPerformed(evt);
            }
        });
        menuListagens.add(listagemPetItem);

        listagemTutorItem.setText("Listar tutores");
        listagemTutorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemTutorItemActionPerformed(evt);
            }
        });
        menuListagens.add(listagemTutorItem);

        listagemAdocaoItem.setText("Listar adoções");
        listagemAdocaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listagemAdocaoItemActionPerformed(evt);
            }
        });
        menuListagens.add(listagemAdocaoItem);

        ListarUsuarios.setText("Listar usuários");
        ListarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarUsuariosActionPerformed(evt);
            }
        });
        menuListagens.add(ListarUsuarios);

        jMenuBar1.add(menuListagens);

        menuRelatorios.setText("Relatórios");

        relatorioPetItem.setText("Relatório dos pets");
        relatorioPetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioPetItemActionPerformed(evt);
            }
        });
        menuRelatorios.add(relatorioPetItem);

        relatorioTutorItem.setText("Relatório dos tutores");
        relatorioTutorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioTutorItemActionPerformed(evt);
            }
        });
        menuRelatorios.add(relatorioTutorItem);

        relatorioAdocaoItem.setText("Relatório de adoções");
        relatorioAdocaoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relatorioAdocaoItemActionPerformed(evt);
            }
        });
        menuRelatorios.add(relatorioAdocaoItem);

        jMenuBar1.add(menuRelatorios);

        menuSair.setText("Sair");
        menuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSairMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registroPetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroPetItemActionPerformed
        CadastroPet cadastroPet = new CadastroPet();
        cadastroPet.setVisible( true );
        dispose();
    }//GEN-LAST:event_registroPetItemActionPerformed

    private void listagemPetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemPetItemActionPerformed
       ListagemPet listagemPet = new ListagemPet();
       listagemPet.setVisible(true);
       dispose();
    }//GEN-LAST:event_listagemPetItemActionPerformed

    private void listagemTutorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemTutorItemActionPerformed
        ListagemTutor listagemTutor = new ListagemTutor();
        listagemTutor.setVisible(true);
        dispose();
    }//GEN-LAST:event_listagemTutorItemActionPerformed

    private void listagemAdocaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listagemAdocaoItemActionPerformed
        ListagemAdocoes listagemAdocao = new ListagemAdocoes();
        listagemAdocao.setVisible(true);
        dispose();
    }//GEN-LAST:event_listagemAdocaoItemActionPerformed

    private void registroTutorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroTutorItemActionPerformed
        CadastroTutor cadastroTutor = new CadastroTutor();
        cadastroTutor.setVisible( true );
        dispose();
    }//GEN-LAST:event_registroTutorItemActionPerformed

    private void registroAdocaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroAdocaoItemActionPerformed
        CadAdocao cadastroAdocao = new CadAdocao( null, null);
        cadastroAdocao.setVisible( true );
        dispose();
    }//GEN-LAST:event_registroAdocaoItemActionPerformed

    private void relatorioPetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioPetItemActionPerformed
        RelatorioPet relatorioPet = new RelatorioPet();
        relatorioPet.setVisible( true );
        dispose();
    }//GEN-LAST:event_relatorioPetItemActionPerformed

    private void relatorioTutorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioTutorItemActionPerformed
        RelatorioTutor relatorioTutor = new RelatorioTutor();
        relatorioTutor.setVisible( true );
        dispose();
    }//GEN-LAST:event_relatorioTutorItemActionPerformed

    private void relatorioAdocaoItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relatorioAdocaoItemActionPerformed
        RelatorioAdocao relatorioAdocao = new RelatorioAdocao();
        relatorioAdocao.setVisible( true );
        dispose();
    }//GEN-LAST:event_relatorioAdocaoItemActionPerformed

    private void menuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSairMouseClicked
        String oi = "";
        
        if ( JOptionPane.showConfirmDialog( this, "Realmente deseja sair?" ) == 0  )
        {
            LoginView login = new LoginView();
            login.setVisible( true );
            dispose();    
        }
    }//GEN-LAST:event_menuSairMouseClicked

    private void CadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadUsuarioActionPerformed
        CadUsuario cadUsuario = new CadUsuario();
        cadUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_CadUsuarioActionPerformed

    private void ListarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarUsuariosActionPerformed
        ListagemUsuario listUsuario = new ListagemUsuario();
        listUsuario.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListarUsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadUsuario;
    private javax.swing.JMenuItem ListarUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem listagemAdocaoItem;
    private javax.swing.JMenuItem listagemPetItem;
    private javax.swing.JMenuItem listagemTutorItem;
    private javax.swing.JMenu menuListagens;
    private javax.swing.JMenu menuRegistros;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSair;
    private javax.swing.JMenuItem registroAdocaoItem;
    private javax.swing.JMenuItem registroPetItem;
    private javax.swing.JMenuItem registroTutorItem;
    private javax.swing.JMenuItem relatorioAdocaoItem;
    private javax.swing.JMenuItem relatorioPetItem;
    private javax.swing.JMenuItem relatorioTutorItem;
    // End of variables declaration//GEN-END:variables
}
