package client.views;

import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.LinkedList;
import javax.swing.text.MaskFormatter;
import server.controller.AdocaoController;
import server.controller.PetController;
import server.controller.TutorController;
import server.model.Adocao;
import server.model.Pet;
import server.model.Tutor;
import server.utilities.GerarPdf;

/**
 *
 * @author luisk
 */
public class RelatorioAdocao extends javax.swing.JFrame {

    AdocaoController adocaoController = new AdocaoController();
    TutorController tutorController = new TutorController();
    PetController petController = new PetController();
    
    MaskFormatter mfData;
    LinkedList columns = new LinkedList();
    
    public RelatorioAdocao() {
        try 
        {
            mfData = new MaskFormatter("##/##/####");
        } 
        catch (ParseException ex)
        {
            System.out.println("Erro na criação da máscara" );
        }
        
        initComponents();
        
        columns.add("ID");
        columns.add("PET");
        columns.add("TUTOR");
        columns.add("DT. SOLIC.");
        columns.add("DT. ADOÇÃO");
        columns.add("STATUS");
        columns.add("INFO.");
        columns.add("JUSTF.");
    }
    
    public LocalDate formatData(String data) 
    {
        try 
        {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(data, formatter);
            return date;
        } 
	catch ( DateTimeParseException e )
        {
            System.out.println("Erro na formatação da data: " + e.getMessage());
        }
        return null;
    }
    
    public boolean verificaData( LocalDate data1, LocalDate data2, LocalDate data )
    {
        if( data1.isEqual( data ) || data2.isEqual( data )  ) return true;
        if( data1.isBefore(data ) && data2.isAfter( data ) ) return true;
        
        return false;
    }
    
    public void addRegisters( LinkedList registers, Adocao adocao, Pet pet, Tutor tutor )
    {
        registers.add( adocao.getId());
        registers.add( pet.getNome() + "[" + pet.getId() + "]" );
        registers.add( tutor.getNome() + "[" + pet.getId() + "]" );
        registers.add( adocao.getDataSolicitacao() != null ? adocao.getDataSolicitacao().toString() : "null" );
        registers.add( adocao.getDataAdocao() != null ? adocao.getDataAdocao().toString() : "null" );
        registers.add( adocao.getStatusAdocao().toString() );
        registers.add( adocao.getInfo() );
        registers.add( adocao.getJustificativa() );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnGerar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextDe = new javax.swing.JFormattedTextField(mfData);
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextAte = new javax.swing.JFormattedTextField(mfData);
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jFormattedTextDe1 = new javax.swing.JFormattedTextField(mfData);
        jLabel12 = new javax.swing.JLabel();
        jFormattedTextAte1 = new javax.swing.JFormattedTextField(mfData);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relatório de Adoção");

        btnVoltar.setBackground(new java.awt.Color(255, 146, 53));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("<");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione os filtros desejados:");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        btnGerar.setBackground(new java.awt.Color(255, 146, 53));
        btnGerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGerar.setText("Gerar");
        btnGerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel3.setText("Status da Adoção:");

        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Aguardando avaliação", "Aprovado", "Reprovado" }));

        jLabel7.setText("Data de Solicitação");

        jLabel8.setText("De");

        jLabel9.setText("Até");

        jFormattedTextAte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextAteActionPerformed(evt);
            }
        });

        jLabel10.setText("Data de Adoção");

        jLabel11.setText("De");

        jLabel12.setText("Até");

        jFormattedTextAte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextAte1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextDe, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextAte, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel7)
                        .addComponent(jLabel3)
                        .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextDe1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel12)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jFormattedTextAte1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel10))
                    .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFormattedTextDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jFormattedTextAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jFormattedTextDe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jFormattedTextAte1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(204, 204, 204)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47))
                            .addComponent(jLabel1))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jFormattedTextAteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextAteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextAteActionPerformed

    private void jFormattedTextAte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextAte1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextAte1ActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        
        boolean isAll = jComboBoxStatus.getSelectedIndex() > 0 ? false : true;
        boolean isDtSolicitacao  = jFormattedTextDe.getText().equals("  /  /    ") ? false : true;
        boolean isDtSolicitacaoAte  = jFormattedTextAte.getText().equals("  /  /    ") ? false : true;
        boolean isDtAdocao  = jFormattedTextDe1.getText().equals("  /  /    ") ? false : true;
        boolean isDtAdocaoAte  = jFormattedTextAte1.getText().equals("  /  /    ") ? false : true;
        
        LinkedList registers = new LinkedList();
        
        LocalDate dtSolicitacao = null;
        LocalDate dtSolicitacaoAte = null;
        LocalDate dtAdocao = null;
        LocalDate dtAdocaoAte = null;
        
        if( isDtSolicitacao && isDtSolicitacaoAte )
        {
            dtSolicitacao = formatData( jFormattedTextDe.getText() );
            dtSolicitacaoAte = formatData( jFormattedTextAte.getText() );
        }
        
        if( isDtAdocao && isDtAdocaoAte )
        {
            dtAdocao = formatData( jFormattedTextDe1.getText() );
            dtAdocaoAte = formatData( jFormattedTextAte1.getText() );
        }
        
        if( !isAll )
        {
            for( Adocao adocao : adocaoController.getAdocoes() )
            {
                if( adocao.getStatusAdocao().equals( Adocao.StatusAdocao.values()[ jComboBoxStatus.getSelectedIndex() -1 ] ) )
                {
                    Tutor tutor = tutorController.buscartTtorPorId( adocao.getTutorId() );
                    Pet pet = petController.buscarPetPorId( adocao.getPetId() );
                    
                    if( isDtSolicitacao && adocao.getDataSolicitacao() != null && verificaData( dtSolicitacao, dtSolicitacaoAte, adocao.getDataSolicitacao() ) )
                    {
                        if( isDtAdocao && adocao.getDataAdocao() != null && verificaData( dtAdocao, dtAdocaoAte, adocao.getDataAdocao() ) )
                        {
                            addRegisters( registers, adocao, pet, tutor );
                        }
                        else if( !isDtAdocao )
                        {
                            addRegisters( registers, adocao, pet, tutor );
                        }
                    }
                    else if( isDtAdocao && adocao.getDataAdocao() != null && verificaData( dtAdocao, dtAdocaoAte, adocao.getDataAdocao() ) )
                    {
                        addRegisters( registers, adocao, pet, tutor );

                    }
                    else if( !isDtSolicitacao && !isDtAdocao )
                    {
                        addRegisters( registers, adocao, pet, tutor );
                    }
                }
            }
        }
        else
        {
            for( Adocao adocao : adocaoController.getAdocoes() )
            {
                Tutor tutor = tutorController.buscartTtorPorId( adocao.getTutorId() );
                Pet pet = petController.buscarPetPorId( adocao.getPetId() );

                if( isDtSolicitacao && adocao.getDataSolicitacao() != null && verificaData( dtSolicitacao, dtSolicitacaoAte, adocao.getDataSolicitacao() ) )
                {
                    if( isDtAdocao && adocao.getDataAdocao() != null && verificaData( dtAdocao, dtAdocaoAte, adocao.getDataAdocao() ) )
                    {
                        addRegisters( registers, adocao, pet, tutor );
                    }
                    else if( !isDtAdocao )
                    {
                        addRegisters( registers, adocao, pet, tutor );
                    }
                }
                else if( isDtAdocao && adocao.getDataAdocao() != null && verificaData( dtAdocao, dtAdocaoAte, adocao.getDataAdocao() ) )
                {
                    addRegisters( registers, adocao, pet, tutor );

                }
                else if( !isDtSolicitacao && !isDtAdocao )
                {
                    addRegisters( registers, adocao, pet, tutor );
                }
            }
        }
        GerarPdf.gerarRelatorioPdf("Relatório de Adoção", columns, registers, new float[]{5,10,15,15,15,15,15,10} );
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioAdocao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioAdocao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JFormattedTextField jFormattedTextAte;
    private javax.swing.JFormattedTextField jFormattedTextAte1;
    private javax.swing.JFormattedTextField jFormattedTextDe;
    private javax.swing.JFormattedTextField jFormattedTextDe1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
