package client.views;

import java.util.LinkedList;
import server.controller.PetController;
import client.views.MenuPrincipal;
import server.model.Pet;
import server.utilities.GerarPdf;
/**
 *
 * @author luisk
 */
public class RelatorioPet extends javax.swing.JFrame {

    PetController petController = new PetController();
    
    LinkedList columns = new LinkedList();
    
    public RelatorioPet() {
    
        initComponents();
        
        for( Pet pet : petController.buscarTodosPets() )
        {
            jComboBoxPet.addItem( pet.getId() + "" );
        }
                
        columns.add("ID PET");
        columns.add("NOME");
        columns.add("IDADE");
        columns.add("DT. SOLIC.");
        columns.add("TIPO");
        columns.add("PORTE");
        columns.add("IMAGEM CAMINHO");
        
        enableCheckBox();
       
    }
    
    public void enableCheckBox()
    {
        if( jComboBoxPet.getSelectedIndex() > 0 )
        {
            jComboBoxPorte.setEnabled( false );
            jComboBoxTipo.setEnabled( false );
            jTextFieldIdade.setEnabled( false );
        }
        else
        {
            jComboBoxPorte.setEnabled( true );
            jComboBoxTipo.setEnabled( true );
            jTextFieldIdade.setEnabled( true );
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBoxPet = new javax.swing.JComboBox<>();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBoxPorte = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldIdade = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Relatório de Pets");

        btnVoltar.setBackground(new java.awt.Color(255, 146, 53));
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("<");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione os filtros desejados:");

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));

        jComboBoxPet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos" }));
        jComboBoxPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPetActionPerformed(evt);
            }
        });

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Gato", "Cachorro" }));

        jLabel4.setText("Tipo");

        btnGerar.setBackground(new java.awt.Color(255, 146, 53));
        btnGerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGerar.setText("Gerar");
        btnGerar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel6.setText("Pet");

        jLabel7.setText("Porte");

        jComboBoxPorte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Pequeno", "Medio", "Grande" }));

        jLabel9.setText("Idade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxPet, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jComboBoxPorte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxPorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(266, 266, 266))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVoltar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(246, 246, 246))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        MenuPrincipal menu = new MenuPrincipal();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jComboBoxPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPetActionPerformed
        enableCheckBox();
    }//GEN-LAST:event_jComboBoxPetActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        
        String petId = jComboBoxPet.getSelectedItem().toString();
        LinkedList registers = new LinkedList();
        boolean isPorte = jComboBoxPorte.getSelectedItem().toString().equals("Todos" ) ? false : true;
        boolean isTipo = jComboBoxTipo.getSelectedItem().toString().equals("Todos" ) ? false : true;
        boolean isIdade = jTextFieldIdade.getText().isBlank() ? false : true;
        int idade = isIdade ? Integer.valueOf( jTextFieldIdade.getText().toString() ) : 0;
        
        if( !petId.equals("Todos") )
        {   
            
            Pet pet = petController.buscarPetPorId( Integer.valueOf( petId ) );
            
            registers.add( pet.getId() );
            registers.add( pet.getNome() );
            registers.add( pet.getIdade() );
            registers.add( pet.getDataDeRegistro().toString() );
            registers.add( pet.getTipoPet().toString() );
            registers.add( pet.getTipoPorte().toString() );
            registers.add( pet.getImagem() );           
        }
        else
        {
            if( isPorte && isTipo )
            {
                String filtro = "tipoPet = " + ( jComboBoxTipo.getSelectedIndex() - 1 ) +" AND "
                        + "tipoPorte = " + ( jComboBoxPorte.getSelectedIndex() -1 )
                        + ( isIdade ? " AND idade = " + idade : "");
                
                for( Pet pet : petController.buscarPetPorFiltro(filtro))
                {
                    registers.add( pet.getId() );
                    registers.add( pet.getNome() );
                    registers.add( pet.getIdade() );
                    registers.add( pet.getDataDeRegistro().toLocalDate().toString() );
                    registers.add( pet.getTipoPet().toString() );
                    registers.add( pet.getTipoPorte().toString() );
                    registers.add( pet.getImagem() );
                }
            }
            else if( isTipo )
            {
                String filtro = "tipoPet = " + ( jComboBoxTipo.getSelectedIndex() -1 )
                        + ( isIdade ? " AND idade = " + idade : "");
                
                for( Pet pet : petController.buscarPetPorFiltro(filtro))
                {
                    registers.add( pet.getId() );
                    registers.add( pet.getNome() );
                    registers.add( pet.getIdade() );
                    registers.add( pet.getDataDeRegistro().toLocalDate().toString() );
                    registers.add( pet.getTipoPet().toString() );
                    registers.add( pet.getTipoPorte().toString() );
                    registers.add( pet.getImagem() );
                }
            }
            else if( isPorte )
            {
                String filtro = "tipoPorte = " + ( jComboBoxPorte.getSelectedIndex() - 1 )
                        + ( isIdade ? " AND idade = " + idade : "");
                
                for( Pet pet : petController.buscarPetPorFiltro(filtro))
                {
                    registers.add( pet.getId() );
                    registers.add( pet.getNome() );
                    registers.add( pet.getIdade() );
                    registers.add( pet.getDataDeRegistro().toLocalDate().toString() );
                    registers.add( pet.getTipoPet().toString() );
                    registers.add( pet.getTipoPorte().toString() );
                    registers.add( pet.getImagem() );
                }
            }
            else if( isIdade )
            {
                String filtro = " idade = " + idade;
                
                for( Pet pet : petController.buscarPetPorFiltro( filtro ) )
                {
                    registers.add( pet.getId() );
                    registers.add( pet.getNome() );
                    registers.add( pet.getIdade() );
                    registers.add( pet.getDataDeRegistro().toLocalDate().toString() );
                    registers.add( pet.getTipoPet().toString() );
                    registers.add( pet.getTipoPorte().toString() );
                    registers.add( pet.getImagem() );
                }
            }
            else
            {
                for( Pet pet : petController.buscarTodosPets() )
                {
                    registers.add( pet.getId() );
                    registers.add( pet.getNome() );
                    registers.add( pet.getIdade() );
                    registers.add( pet.getDataDeRegistro().toLocalDate().toString() );
                    registers.add( pet.getTipoPet().toString() );
                    registers.add( pet.getTipoPorte().toString() );
                    registers.add( pet.getImagem() );
                }
            }
        }
        
        GerarPdf.gerarRelatorioPdf("Relatório de Pets", columns, registers, new float[]{10,20,10,15,20,15,10} );
    }//GEN-LAST:event_btnGerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBoxPet;
    private javax.swing.JComboBox<String> jComboBoxPorte;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldIdade;
    // End of variables declaration//GEN-END:variables
}
